### ISSUE TITLE
Script isn't working on LMDE

### ISSUE THREAD

**Issue by Glorung** [AktasC/epitech-tools#1]
Something is not working, "too many arguments"

Commande éxecuté avec ./install.sh vincent.gendron@epitech.eu 2>error

Log d'erreur :
[error.txt](https://github.com/AktasC/epitech-tools/files/821376/error.txt)

Log inix :
[os.txt](https://github.com/AktasC/epitech-tools/files/821385/os.txt)

**Comment by AktasC** [comment]
EDIT : 

Apaprently the problem comes from the system function "test" which is mandatory for the script to operate properly.
I think that it might never work for LMDE and that, for that specific system, I'd need to create a specific install.sh

Hope you understand.

Regards,
AktasC
